language: ruby

sudo: false
cache:
  bundler: true
  directories:
    - $HOME/.m2

before_script:
  - mysql -uroot -e 'create database killbill_test;'

notifications:
  email:
    - kill-bill-commits@googlegroups.com

env:
  global:
    - JRUBY_OPTS='-J-Xmx1024M'
  matrix:
    - AR_ADAPTER='mariadb' AR_USERNAME='root' AR_PASSWORD='' AR_DATABASE='killbill_test'
    - AR_ADAPTER='sqlite3' AR_DATABASE='test.db'

rvm:
  - jruby-1.7.16
  - jruby-20mode # latest 1.7.x
  - jruby-head

gemfile:
  - Gemfile
  - Gemfile.head

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

matrix:
  allow_failures:
    - rvm: jruby-head
    - jdk: oraclejdk8
    - gemfile: Gemfile.head
  fast_finish: true
