language: ruby

sudo: false
cache: bundler

notifications:
  email:
    - kill-bill-commits@googlegroups.com

rvm:
  - jruby-1.7.16
  - jruby-20mode # latest 1.7.x
  - jruby-head

gemfile:
  - Gemfile
  - Gemfile.head

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

matrix:
  allow_failures:
    - rvm: jruby-head
    - jdk: oraclejdk8
    - gemfile: Gemfile.head
