language: ruby

notifications:
  email:
    - kill-bill-commits@googlegroups.com

rvm:
  - jruby-1.7.16
  - jruby-20mode # latest 1.7.x
  - jruby-head

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

matrix:
  allow_failures:
    - rvm: jruby-head
  exclude:
    - rvm: jruby-head
      jdk: openjdk6
